plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

// The Wear OS Data Layer only connects apps that share the same applicationId
// AND signing certificate, so sign with the same keystore as the phone app.
// Defaults to the debug keystore generated by `npx expo prebuild`; override with
// -PgymbuddyKeystore=... (plus the password/alias properties) for other keys.
val phoneKeystore = file(
    providers.gradleProperty("gymbuddyKeystore").orNull ?: "../../android/app/debug.keystore"
)
if (!phoneKeystore.exists()) {
    logger.warn(
        "WARNING: $phoneKeystore not found. Run `npx expo prebuild -p android` in the repo root " +
            "first, otherwise the watch app will not be able to talk to the phone app."
    )
}

android {
    namespace = "com.gymbuddy.wear"
    compileSdk = 36

    defaultConfig {
        // Must match the phone app's package (app.json -> android.package).
        applicationId = "com.gymbuddy.app"
        minSdk = 30
        targetSdk = 35
        versionCode = 1
        versionName = "1.0.0"
    }

    signingConfigs {
        if (phoneKeystore.exists()) {
            create("phone") {
                storeFile = phoneKeystore
                storePassword = providers.gradleProperty("gymbuddyKeystorePassword").orNull ?: "android"
                keyAlias = providers.gradleProperty("gymbuddyKeyAlias").orNull ?: "androiddebugkey"
                keyPassword = providers.gradleProperty("gymbuddyKeyPassword").orNull ?: "android"
            }
        }
    }

    buildTypes {
        val signing = signingConfigs.findByName("phone") ?: signingConfigs.getByName("debug")
        debug {
            signingConfig = signing
        }
        release {
            signingConfig = signing
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation("com.google.android.gms:play-services-wearable:19.0.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.9.0")
    implementation("androidx.activity:activity-compose:1.10.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.wear.compose:compose-material:1.4.1")
    implementation("androidx.wear.compose:compose-foundation:1.4.1")
}
